# -- mode: ruby --
# vi: set ft=ruby :
servers = {
  "PMensajes" => { :ip => "192.168.56.2", :cpus => 1, :mem => 1024, :ssh_port=>2222 },
  "Broker" => { :ip => "192.168.56.3", :cpus => 1, :mem => 1024, :ssh_port=>2223 },
  "Consumidor1" => { :ip => "192.168.56.4", :cpus => 1, :men => 1024, :ssh_port=>2224 },
  "Consumidor2" => { :ip => "192.168.56.5", :cpus => 1, :men => 1024, :ssh_port=>2225 }
}
Vagrant.configure("2") do |config|
  servers.each_with_index do |(hostname, info), index|
     config.vm.define hostname do |cfg|
       cfg.vm.provider :virtualbox do |vb, override| 
         config.vm.box = "bento/ubuntu-18.04"
         override.vm.network "private_network", ip: "#{info[:ip]}"
         #Fix SSH forwarded port
         override.vm.network "forwarded_port", guest: 22, host:"#{info[:ssh_port]}", id: "ssh", auto_correct: true
         override.vm.hostname = hostname
         override.vm.provision "file", source: ".ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/public_key"
         override.vm.provision "shell", inline: "cat /home/vagrant/.ssh/public_key >> /home/vagrant/.ssh/authorized_keys"
         override.vm.provision "shell", inline: "rm /home/vagrant/.ssh/public_key"
         vb.name = hostname
	 config.ssh.private_key_path = [".ssh/id_rsa", "~/.vagrant.d/insecure_private_key"]
	 config.vm.provision "file", source: ".ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
	 config.ssh.insert_key = false
       end
     end
  end
  #provision for servers
    config.vm.provision "ansible" do |ansible|
            ansible.inventory_path = 'hosts'
            ansible.verbose = 'vvv'
            ansible.playbook = 'playbooks/servers.yml'
    end
end